services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"      # HTTP Port
      - "443:443"    # HTTPS Port
    volumes:
      - type: bind # Nginx Main Config
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind # User Config Directory
        source: ./user.d
        target: /etc/nginx/user.d
        read_only: true
      - type: bind # SSL Directory
        source: ./ssl
        target: /etc/nginx/ssl
        read_only: true
    restart: unless-stopped
