services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"      # HTTP Port
      - "443:443"    # HTTPS Port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro      # Nginx Main Config
      - ./user.d:/etc/nginx/user.d:ro             # User Config Directory
      - ./ssl:/etc/nginx/ssl:ro                 # SSL Directory
    restart: unless-stopped
